// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RfidAPI.Data;

namespace RfidAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("RfidAPI.Models.DeviceCount", b =>
                {
                    b.Property<int?>("deviceCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("deviceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("nowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("deviceCountId");

                    b.ToTable("DeviceCount");
                });

            modelBuilder.Entity("RfidAPI.Models.Equipment", b =>
                {
                    b.Property<int>("deviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("deviceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("imageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("deviceId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RfidAPI.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("from_UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("from_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("log")
                        .HasColumnType("TEXT");

                    b.Property<int>("requestStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("to_UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("to_time")
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("from_UserId");

                    b.HasIndex("to_UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("RfidAPI.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("role_name")
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("RfidAPI.Models.Repo", b =>
                {
                    b.Property<int>("RepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("info")
                        .HasColumnType("TEXT");

                    b.Property<int>("managerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RepoId");

                    b.HasIndex("managerId");

                    b.ToTable("Repo");
                });

            modelBuilder.Entity("RfidAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("faceInfo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("permissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("permissionId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RfidAPI.Models.Log", b =>
                {
                    b.HasOne("RfidAPI.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("from_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidAPI.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("to_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("RfidAPI.Models.Repo", b =>
                {
                    b.HasOne("RfidAPI.Models.User", "manager")
                        .WithMany()
                        .HasForeignKey("managerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("RfidAPI.Models.User", b =>
                {
                    b.HasOne("RfidAPI.Models.Permission", "permission")
                        .WithMany()
                        .HasForeignKey("permissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");
                });
#pragma warning restore 612, 618
        }
    }
}
